# add a role:[hawq_operator_role] and give all needed permission to it.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zk_operator_role
#  namespace: default
rules:
- apiGroups:
  - zookeeper.database.apache.com
  resources:
  - zookeeperclusters
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  - apps
  - autoscaling
  resources:
  - pods
  - services
  - configmaps
  - endpoints
  - persistentvolumes
  - persistentvolumeclaims
  - events
  - endpoints
  - deployments
  - statefulsets
  - horizontalpodautoscalers
  verbs:
  - "*"
