apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper-operator
    spec:
      containers:
      - name: zookeeper-operator
        image: blafrisch/zookeeper-operator:latest
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name