---
apiVersion: v1
kind: Service
metadata:
  name: solr
spec:
  ports:
  - port: 18983
    name: solr-port
  clusterIP: None
  selector:
    app: solr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: solr
  name: solr-node
  namespace: default
spec:
  serviceName: "solr"
  selector:
    matchLabels:
      app: solr
  replicas: 2
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - name: solr-node
        image: solr:7.3.1-alpine
        imagePullPolicy: Always
